modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT License"

[[mods]]
modId = "management"
version = "${file.jarVersion}"
displayName = "Management"
authors = "sciwhiz12"
description = '''
* Server administration, moderation, and management. *

A server management mod.
'''

[[dependencies.management]]
modId = "forge"
mandatory = true
versionRange = "[34.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.management]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3]"
ordering = "NONE"
side = "BOTH"
