modLoader = "javafml"
loaderVersion = "[34,36)"
license = "MIT License"

[[mods]]
modId = "oversight"
version = "${file.jarVersion}"
displayName = "Oversight"
authors = "sciwhiz12"
description = '''
* Server administration, moderation, and management. *

A server management mod.
'''

[[dependencies.oversight]]
modId = "forge"
mandatory = true
versionRange = "[34.1.0,36)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oversight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "BOTH"
